const fs = require('fs');
const path = require('path');
const file = path.join(__dirname, 'regenerated_from_source', '經文.html');
let html = fs.readFileSync(file, 'utf8');
const old = '<a href="index.html">首頁</a>　<a href="綱目.html">綱目</a>　<strong>經文</strong>';
const nav = '<nav id="site-nav" aria-label="主要導覽"><a href="index.html">首頁</a><a href="綱目.html">綱目</a><a href="經文.html">經文</a><a href="週一.html">週一</a><a href="週二.html">週二</a><a href="週三.html">週三</a><a href="週四.html">週四</a><a href="週五.html">週五</a><a href="週六.html">週六</a></nav>';
if (!html.includes(old)) throw new Error('找不到經文頁原導覽。');
html = html.replace(old, nav);
fs.writeFileSync(file, html, 'utf8');
console.log('Scripture navigation fixed.');
